---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-bm25-deployment
  namespace: aviation-safety
  labels:
    app: backend-bm25-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-bm25
  template:
    metadata:
      labels:
        app: backend-bm25
    spec:
      containers:
        - name: backend-bm25-container
          image: backend-bm25:latest
          imagePullPolicy: Never
          env:
            - name: MAIN_DRIVER_URL
              value: http://backend-main-service:8000
            - name: S3_BUCKET
              value: asrs-storage-anabel-2026
            - name: S3_KEY
              value: bm25/bm25_asrs_full_index.pkl.gz
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_S3
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_KEY_S3
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_REGION_S3
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8001
            initialDelaySeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 120
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8001
            failureThreshold: 30
            periodSeconds: 10
