---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: aviation-safety
  labels:
    app: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: frontend:latest
          env:
            - name: MAIN_DRIVER_URL
              value: http://backend-main-service:8000
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
