---
apiVersion: v1
kind: Service
metadata:
  name: backend-main-service
  namespace: aviation-safety
  labels:
    app: backend-main-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: backend-main
