services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      # Mount BM25 index so we don't need to rebuild if it changes
      - ./backend/src/models:/app/src/models
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
