---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aviation-safety
resources:
  - ../../base
  - ./namespace.yaml
  - virtual-service.yaml
  - hpa-frontend.yaml
  - hpa-backend-main.yaml
  - hpa-backend-bm25.yaml
  - hpa-backend-embeddings.yaml
images:
  - name: frontend
    newName: 034362054263.dkr.ecr.us-east-1.amazonaws.com/aviation-safety-capstone-spring-2026/frontend
    newTag: "latest"
  - name: backend-main
    newName: 034362054263.dkr.ecr.us-east-1.amazonaws.com/aviation-safety-capstone-spring-2026/backend-main
    newTag: "latest"
  - name: backend-bm25
    newName: 034362054263.dkr.ecr.us-east-1.amazonaws.com/aviation-safety-capstone-spring-2026/backend-bm25
    newTag: "latest"
  - name: backend-embeddings
    newName: 034362054263.dkr.ecr.us-east-1.amazonaws.com/aviation-safety-capstone-spring-2026/backend-embeddings
    newTag: "latest"
