export const allColumns = [
  { "value": "acn_num_ACN", "label": "ACN Number" },
  { "value": "Time_Date", "label": "Date" },
  { "value": "Time.1_Local Time Of Day", "label": "Local Time of Day" },
  { "value": "Place_Locale Reference", "label": "Locale Reference" },
  { "value": "Place.1_State Reference", "label": "State Reference" },
  { "value": "Place.2_Relative Position.Angle.Radial", "label": "Relative Position Angle (Radial)" },
  { "value": "Place.3_Relative Position.Distance.Nautical Miles", "label": "Relative Position Distance (NM)" },
  { "value": "Place.4_Altitude.AGL.Single Value", "label": "Altitude AGL" },
  { "value": "Place.5_Altitude.MSL.Single Value", "label": "Altitude MSL" },
  { "value": "Environment_Flight Conditions", "label": "Flight Conditions" },
  { "value": "Environment.1_Weather Elements / Visibility", "label": "Weather / Visibility" },
  { "value": "Environment.2_Work Environment Factor", "label": "Work Environment Factor" },
  { "value": "Environment.3_Light", "label": "Light Conditions" },
  { "value": "Environment.4_Ceiling", "label": "Ceiling" },
  { "value": "Environment.5_RVR.Single Value", "label": "RVR" },
  { "value": "Aircraft 1_ATC / Advisory", "label": "Aircraft 1 ATC / Advisory" },
  { "value": "Aircraft 1.1_Aircraft Operator", "label": "Aircraft 1 Operator" },
  { "value": "Aircraft 1.2_Make Model Name", "label": "Aircraft 1 Make / Model" },
  { "value": "Aircraft 1.3_Aircraft Zone", "label": "Aircraft 1 Zone" },
  { "value": "Aircraft 1.4_Crew Size", "label": "Aircraft 1 Crew Size" },
  { "value": "Aircraft 1.5_Operating Under FAR Part", "label": "Aircraft 1 FAR Part" },
  { "value": "Aircraft 1.6_Flight Plan", "label": "Aircraft 1 Flight Plan" },
  { "value": "Aircraft 1.7_Mission", "label": "Aircraft 1 Mission" },
  { "value": "Aircraft 1.8_Nav In Use", "label": "Aircraft 1 Navigation in Use" },
  { "value": "Aircraft 1.9_Flight Phase", "label": "Aircraft 1 Flight Phase" },
  { "value": "Aircraft 1.10_Route In Use", "label": "Aircraft 1 Route in Use" },
  { "value": "Aircraft 1.11_Airspace", "label": "Aircraft 1 Airspace" },
  { "value": "Aircraft 1.12_Maintenance Status.Maintenance Deferred", "label": "Aircraft 1 Maintenance Deferred" },
  { "value": "Aircraft 1.13_Maintenance Status.Records Complete", "label": "Aircraft 1 Maintenance Records Complete" },
  { "value": "Aircraft 1.14_Maintenance Status.Released For Service", "label": "Aircraft 1 Released for Service" },
  { "value": "Aircraft 1.15_Maintenance Status.Required / Correct Doc On Board", "label": "Aircraft 1 Required Docs On Board" },
  { "value": "Aircraft 1.16_Maintenance Status.Maintenance Type", "label": "Aircraft 1 Maintenance Type" },
  { "value": "Aircraft 1.17_Maintenance Status.Maintenance Items Involved", "label": "Aircraft 1 Maintenance Items Involved" },
  { "value": "Aircraft 1.18_Cabin Lighting", "label": "Aircraft 1 Cabin Lighting" },
  { "value": "Aircraft 1.19_Number Of Seats.Number", "label": "Aircraft 1 Number of Seats" },
  { "value": "Aircraft 1.20_Passengers On Board.Number", "label": "Aircraft 1 Passengers On Board" },
  { "value": "Aircraft 1.21_Crew Size Flight Attendant.Number Of Crew", "label": "Aircraft 1 Flight Attendant Crew Size" },
  { "value": "Aircraft 1.22_Airspace Authorization Provider (UAS)", "label": "Aircraft 1 UAS Airspace Authorization Provider" },
  { "value": "Aircraft 1.23_Operating Under Waivers / Exemptions / Authorizations (UAS)", "label": "Aircraft 1 UAS Waivers / Exemptions" },
  { "value": "Aircraft 1.24_Waivers / Exemptions / Authorizations (UAS)", "label": "Aircraft 1 UAS Waiver Details" },
  { "value": "Aircraft 1.25_Airworthiness Certification (UAS)", "label": "Aircraft 1 UAS Airworthiness Certification" },
  { "value": "Aircraft 1.26_Weight Category (UAS)", "label": "Aircraft 1 UAS Weight Category" },
  { "value": "Aircraft 1.27_Configuration (UAS)", "label": "Aircraft 1 UAS Configuration" },
  { "value": "Aircraft 1.28_Flight Operated As (UAS)", "label": "Aircraft 1 UAS Flight Operated As" },
  { "value": "Aircraft 1.29_Flight Operated with Visual Observer (UAS)", "label": "Aircraft 1 UAS Visual Observer" },
  { "value": "Aircraft 1.30_Control Mode (UAS)", "label": "Aircraft 1 UAS Control Mode" },
  { "value": "Aircraft 1.31_Flying In / Near / Over (UAS)", "label": "Aircraft 1 UAS Flying In / Near / Over" },
  { "value": "Aircraft 1.32_Passenger Capable (UAS)", "label": "Aircraft 1 UAS Passenger Capable" },
  { "value": "Aircraft 1.33_Type (UAS)", "label": "Aircraft 1 UAS Type" },
  { "value": "Aircraft 1.34_Number of UAS Being Controlled (UAS)", "label": "Aircraft 1 Number of UAS Controlled" },
  { "value": "Component_Aircraft Component", "label": "Aircraft Component" },
  { "value": "Component.1_Manufacturer", "label": "Component Manufacturer" },
  { "value": "Component.2_Aircraft Reference", "label": "Component Aircraft Reference" },
  { "value": "Component.3_Problem", "label": "Component Problem" },
  { "value": "Aircraft 2_ATC / Advisory", "label": "Aircraft 2 ATC / Advisory" },
  { "value": "Aircraft 2.1_Aircraft Operator", "label": "Aircraft 2 Operator" },
  { "value": "Aircraft 2.2_Make Model Name", "label": "Aircraft 2 Make / Model" },
  { "value": "Aircraft 2.4_Crew Size", "label": "Aircraft 2 Crew Size" },
  { "value": "Aircraft 2.5_Operating Under FAR Part", "label": "Aircraft 2 FAR Part" },
  { "value": "Aircraft 2.6_Flight Plan", "label": "Aircraft 2 Flight Plan" },
  { "value": "Aircraft 2.7_Mission", "label": "Aircraft 2 Mission" },
  { "value": "Aircraft 2.8_Nav In Use", "label": "Aircraft 2 Navigation in Use" },
  { "value": "Aircraft 2.9_Flight Phase", "label": "Aircraft 2 Flight Phase" },
  { "value": "Aircraft 2.10_Route In Use", "label": "Aircraft 2 Route in Use" },
  { "value": "Aircraft 2.11_Airspace", "label": "Aircraft 2 Airspace" },
  { "value": "Aircraft 2.12_Maintenance Status.Maintenance Deferred", "label": "Aircraft 2 Maintenance Deferred" },
  { "value": "Aircraft 2.14_Maintenance Status.Released For Service", "label": "Aircraft 2 Released for Service" },
  { "value": "Aircraft 2.16_Maintenance Status.Maintenance Type", "label": "Aircraft 2 Maintenance Type" },
  { "value": "Aircraft 2.17_Maintenance Status.Maintenance Items Involved", "label": "Aircraft 2 Maintenance Items Involved" },
  { "value": "Aircraft 2.23_Operating Under Waivers / Exemptions / Authorizations (UAS)", "label": "Aircraft 2 UAS Waivers / Exemptions" },
  { "value": "Aircraft 2.24_Waivers / Exemptions / Authorizations (UAS)", "label": "Aircraft 2 UAS Waiver Details" },
  { "value": "Aircraft 2.26_Weight Category (UAS)", "label": "Aircraft 2 UAS Weight Category" },
  { "value": "Aircraft 2.27_Configuration (UAS)", "label": "Aircraft 2 UAS Configuration" },
  { "value": "Aircraft 2.28_Flight Operated As (UAS)", "label": "Aircraft 2 UAS Flight Operated As" },
  { "value": "Aircraft 2.31_Flying In / Near / Over (UAS)", "label": "Aircraft 2 UAS Flying In / Near / Over" },
  { "value": "Aircraft 2.34_Number of UAS Being Controlled (UAS)", "label": "Aircraft 2 Number of UAS Controlled" },
  { "value": "Person 1_Location Of Person", "label": "Person 1 Location" },
  { "value": "Person 1.1_Location In Aircraft", "label": "Person 1 Location in Aircraft" },
  { "value": "Person 1.2_Reporter Organization", "label": "Person 1 Reporter Organization" },
  { "value": "Person 1.3_Function", "label": "Person 1 Function" },
  { "value": "Person 1.4_Qualification", "label": "Person 1 Qualification" },
  { "value": "Person 1.5_Experience", "label": "Person 1 Experience" },
  { "value": "Person 1.6_Cabin Activity", "label": "Person 1 Cabin Activity" },
  { "value": "Person 1.7_Human Factors", "label": "Person 1 Human Factors" },
  { "value": "Person 1.8_Communication Breakdown", "label": "Person 1 Communication Breakdown" },
  { "value": "Person 1.9_UAS Communication Breakdown", "label": "Person 1 UAS Communication Breakdown" },
  { "value": "Person 1.10_ASRS Report Number.Accession Number", "label": "Person 1 ASRS Accession Number" },
  { "value": "Person 2_Location Of Person", "label": "Person 2 Location" },
  { "value": "Person 2.1_Location In Aircraft", "label": "Person 2 Location in Aircraft" },
  { "value": "Person 2.2_Reporter Organization", "label": "Person 2 Reporter Organization" },
  { "value": "Person 2.3_Function", "label": "Person 2 Function" },
  { "value": "Person 2.4_Qualification", "label": "Person 2 Qualification" },
  { "value": "Person 2.5_Experience", "label": "Person 2 Experience" },
  { "value": "Person 2.6_Cabin Activity", "label": "Person 2 Cabin Activity" },
  { "value": "Person 2.7_Human Factors", "label": "Person 2 Human Factors" },
  { "value": "Person 2.8_Communication Breakdown", "label": "Person 2 Communication Breakdown" },
  { "value": "Person 2.9_UAS Communication Breakdown", "label": "Person 2 UAS Communication Breakdown" },
  { "value": "Person 2.10_ASRS Report Number.Accession Number", "label": "Person 2 ASRS Accession Number" },
  { "value": "Events_Anomaly", "label": "Event Anomaly" },
  { "value": "Events.1_Miss Distance", "label": "Miss Distance" },
  { "value": "Events.2_Were Passengers Involved In Event", "label": "Passengers Involved in Event" },
  { "value": "Events.3_Detector", "label": "Event Detector" },
  { "value": "Events.4_When Detected", "label": "When Detected" },
  { "value": "Events.5_Result", "label": "Event Result" },
  { "value": "Assessments_Contributing Factors / Situations", "label": "Contributing Factors / Situations" },
  { "value": "Assessments.1_Primary Problem", "label": "Primary Problem" },
  { "value": "Report 1_Narrative", "label": "Report 1 Narrative" },
  { "value": "Report 1.1_Callback", "label": "Report 1 Callback" },
  { "value": "Report 2_Narrative", "label": "Report 2 Narrative" },
  { "value": "Report 2.1_Callback", "label": "Report 2 Callback" },
  { "value": "Report 1.2_Synopsis", "label": "Synopsis" }
]